"""Stock universe definitions for NIFTY 50 and S&P 500 Top 50."""

NIFTY50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BPCL.NS", "BHARTIARTL.NS",
    "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS",
    "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
    "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS",
    "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS", "SHRIRAMFIN.NS",
    "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS"
]

SP500_TOP50 = [
    "NVDA", "AAPL", "MSFT", "GOOGL", "AMZN", "META", "AVGO", "TSLA", "BRK-B", "LLY",
    "JPM", "V", "WMT", "UNH", "XOM", "MA", "PG", "JNJ", "COST", "HD",
    "ABBV", "CVX", "ORCL", "NFLX", "CRM", "AMD", "BAC", "KO", "ACN", "ABT",
    "TMO", "DIS", "PFE", "DHR", "TXN", "VZ", "PM", "WFC", "NKE", "ADBE",
    "COP", "CSCO", "SPGI", "HON", "LIN", "CAT", "RTX", "UNP", "INTC", "LOW"
]

UNIVERSES = {
    "NIFTY 50": NIFTY50,
    "S&P 500 Top 50": SP500_TOP50
}